import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Header } from "@/components/layout/Header";
import { Navbar } from "@/components/layout/Navbar";
import { Main } from "@/components/views/Main";
import { Experiences } from "@/components/views/Experiences";
import { Stack } from "@/components/views/Stack";
import { Works } from "@/components/views/Works";
import { Examples } from "@/components/views/Examples";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio Bogdan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Header />
        <Navbar />
        <Main />
        <Experiences />
        <Stack />
        <Works />
        <Examples />
      </main>
    </>
  );
}
